[workspace]
resolver = "2"
members = [
    "program",
    "cli",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/aisoh877/solana-rental-escrow"

[workspace.dependencies]
anyhow = "1.0"
borsh = { version = "1.5", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
solana-client = "1.18.26"
solana-program = "1.18.26"
solana-program-test = "1.18.26"
solana-sdk = "1.18.26"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
