[package]
name = "rental-escrow-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
borsh.workspace = true
clap.workspace = true
rental-escrow-program = { path = "../program", features = ["no-entrypoint"] }
solana-client.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
